<?php

$container['lists'] = [
    'user_types' => [
        'admin' => 0,
        'user' => 1,
        'company' => 2,
    ],
    'user_roles' => [
        'admin' => [
            'supervisor' => 0,
            'manager' => 1,
            'editor' => 2,
        ],
        'user' => [
            'data' => 0,
            'lead' => 1,
            'customer' => 2,
            'partner' => 3,
            'member' => 4,
            'leader' => 5,
            'stuff' => 6,
        ],
        'company' => [
            'data' => 0,
            'lead' => 1,
            'customer' => 2,
            'partner' => 3,
        ]
    ],
    'gender_types' => [
        'male' => 0,
        'female' => 1,
        'unknown' => 2
    ],
    'status_types' => [
        'inactive' => 0,
        'active' => 1,
    ],
    'secret_types' => [
        'token' => 0,
        'password' => 1,
        'validation' => 2
    ],
    'permission_types' => [
        'standard' => 0,
        'spezial' => 1
    ],
    'permission_states' => [
        'get_one' => 0,
        'get_all' => 1,
        'read' => 2,
        'update' => 3,
        'delete' => 4,
        'create' => 5,
        'write' => 6,
        'admin_get_one' => 7,
        'admin_get_all' => 8,
        'admin_read' => 9,
        'admin_update' => 10,
        'admin_delete' => 11,
        'admin_create' => 12,
        'admin_write' => 13
    ],
    'relations' => [
        'users' => 0,
        'articles' => 1,
        'progress' => 2,
        'vita' => 3,
        'projects' => 4,
        'posts' => 5,
        'tasks' => 6,
        'reports' => 7,
        'accounts' => 8,
        'status' => 9,
        'status_details' => 10,
        'trophies' => 11,
        'records' => 12,
        'comment' => 13,
        'like' => 14,
        'tag' => 15,
        'media' => 16,
        'position' => 17,
        'adress' => 18,
        'contact' => 19,
        'bank' => 20,
        'ip' => 21,
        'lists' => 22,
        'secret' => 23,
        'relations' => 24,
        'date' => 25,
        'description' => 26,
        'gender' => 27,
        'permission' => 28,
        'table_field' => 29,
        'field' => 30
    ],
    'notifications' => [
        'NO_DATABASE_CONNECTION' => 0,
        'UNAVAILABLE' => 1,
        'VALID' => 2,
        'TO_SHORT' => 3,
        'TO_LONG' => 4,
        'NO_STRING' => 5,
        'NO_NUMBER' => 6,
        'NO_INTEGER' => 7,
        'NO_DATE' => 8,
        'PERMISSION_DENIED' => 9,
        'UNKNOWN_USER_TYPE' => 10,
        'TYPE_ADMIN_DENIED' => 11,
        'UNKNOWN_CONTACT_TYPE' => 12,
        'NO_EMAIL' => 13,
        'MISSING_MAIL_FROM' => 14,
        'MISSING_MAIL_TO' => 15,
        'MISSING_MAIL_SUBJECT' => 16,
        'MISSING_MAIL_MESSAGE' => 17,
        'MAIL_SENDING_SUCCESS' => 18,
        'MAIL_SENDING_FAILURE' => 19,
        'NO_DYNAMIC_TABLE_NAME' => 20,
        'UNKNOWN_SECRET_TYPE' => 21,
        'MISSING_REQUIRED_PARAMS' => 22,
        'INVALID_PASSWORD' => 23,
        'NOT_ENOUGH_JOIN_PARAMS' => 24,
        'MISSING_JOIN_TYPE' => 25,
        'UNKNOWN_JOIN_TYPE' => 26,
        'INVALID_JOIN_PARAM' => 27,
        'EXECUTE_ERROR' => 28,
        'INVALID_COLUMNS_REQUESTED' => 29,
        'UNKNOWN_USER' => 30,
        'INVALID_TOKEN' => 31,
        'EXPIRED_TOKEN' => 32,
        'EMAIL_ALREADY_EXISTS' => 33,
        'INVALID_UID' => 34,
        'UNKNOWN_EMAIL' => 35,
        'UNREGISTERED_USER' => 36,
        'UNKNOWN_PERMISSION_TYPE' => 37,
        'FIELD_ALREADY_EXISTS' => 38,
        'FIELD_NOT_EXISTS' => 39,
        'UNKNOWN_FIELD_DATA_TYPE' => 40
    ],
];